name: Test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Create Docker tag
        id: tag
        uses: InfraWay/gh-create-docker-tag@main
      - name: Get the tag
        run: |
          echo "The tag is ${{ steps.tag.outputs.tag }}"
          echo "Image name is ${{ steps.tag.outputs.name }}"
